/** 内联图标名 —— 与 design-system/components/Icon.tsx 的 IconName 对齐（子集）。 */
export type IconName =
  | 'github'
  | 'gmail'
  | 'discord'
  | 'telegram'
  | 'spotify'
  | 'bilibili'
  | 'external'
  | 'arrowRight'
  | 'sun'
  | 'moon'
  | 'monitor'
  | 'star'
  | 'fork'
  | 'folder'
  | 'people'
  | 'commit'
  | 'clock'
  | 'calendar'
  | 'chevronUp'
