/**
 * Generates Material Design 3 color tokens (../theme/colors.css) from a seed color.
 *
 * Uses Google's official `@material/material-color-utilities` — the `DynamicScheme`
 * + `MaterialDynamicColors` API (the same machinery behind Material Theme Builder) —
 * to produce the full M3 tonal palette and map it onto the M3 color roles for both
 * light and dark schemes. The scheme includes the surface-container family.
 *
 * Usage (from the repo root, with @material/material-color-utilities and tsx
 * installed as devDependencies — v0.4.0 of that package has extension-less
 * internal ESM imports, so plain `node` cannot resolve it; tsx can, which is
 * why the source project runs this script via tsx):
 *   npx tsx design-system/scripts/gen-theme.mjs           # default seed (#18F741)
 *   SEED_COLOR=#006A6A npx tsx design-system/scripts/gen-theme.mjs
 * (On Windows cmd: `set SEED_COLOR=#006A6A && npx tsx ...`; PowerShell:
 *  `$env:SEED_COLOR='#006A6A'; npx tsx ...`.)
 *
 * The generated file is committed so the runtime has zero JS dependency for theming.
 * Only difference from the source project's scripts/gen-theme.mjs: OUT resolves to
 * this pack's own theme/ folder.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import {
  argbFromHex,
  DynamicScheme,
  Hct,
  hexFromArgb,
  MaterialDynamicColors,
  Variant,
} from '@material/material-color-utilities'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../theme/colors.css')

const SEED = process.env.SEED_COLOR ?? '#18F741'

// M3 color roles (v1.2+ token set). Kept explicit so a role added by the spec is
// visibly missing here rather than silently skipped.
const ROLES = [
  'primary',
  'onPrimary',
  'primaryContainer',
  'onPrimaryContainer',
  'secondary',
  'onSecondary',
  'secondaryContainer',
  'onSecondaryContainer',
  'tertiary',
  'onTertiary',
  'tertiaryContainer',
  'onTertiaryContainer',
  'error',
  'onError',
  'errorContainer',
  'onErrorContainer',
  'background',
  'onBackground',
  'surface',
  'onSurface',
  'surfaceVariant',
  'onSurfaceVariant',
  'outline',
  'outlineVariant',
  'surfaceContainerLowest',
  'surfaceContainerLow',
  'surfaceContainer',
  'surfaceContainerHigh',
  'surfaceContainerHighest',
  'surfaceDim',
  'surfaceBright',
  'surfaceTint',
  'inverseSurface',
  'inverseOnSurface',
  'inversePrimary',
  'shadow',
  'scrim',
]

const toKebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)

const sourceArgb = argbFromHex(SEED)
const sourceHct = Hct.fromInt(sourceArgb)

// Build light and dark schemes with the same settings Material Theme Builder uses
// by default (Tonal Spot variant, standard contrast).
const buildScheme = (isDark) =>
  new DynamicScheme({
    sourceColorHct: sourceHct,
    variant: Variant.TONAL_SPOT,
    isDark,
    contrastLevel: 0,
  })

const missing = ROLES.filter((role) => MaterialDynamicColors[role] === undefined)
if (missing.length > 0) {
  console.error(`[gen-theme] ERROR: unknown roles: ${missing.join(', ')}`)
  process.exit(1)
}

const renderBlock = (scheme) =>
  ROLES.map((role) => {
    const argb = MaterialDynamicColors[role].getArgb(scheme)
    return `  --md-sys-color-${toKebab(role)}: #${hexFromArgb(argb).replace(/^#/, '').toLowerCase()};`
  }).join('\n')

const light = buildScheme(false)
const dark = buildScheme(true)

const css = `/* Auto-generated by scripts/gen-theme.mjs — do not edit by hand.
   Run \`npm run theme:gen\` (optionally with SEED_COLOR=#hex) to regenerate.
   Seed color: ${SEED} · Variant: Tonal Spot */
:root {
${renderBlock(light)}
}

/* Dark scheme: applied either by the system preference (when no manual override
   is set) or by [data-theme="dark"] from the theme toggle. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${renderBlock(dark)}
  }
}

:root[data-theme='dark'] {
${renderBlock(dark)}
}
`

writeFileSync(OUT, css)
console.log(`[gen-theme] wrote ${OUT} (seed ${SEED})`)
